from unittest.mock import MagicMock

import pytest

from flext_db_oracle import FlextDbOracleConfig

class TestOracleIntegration:
    @pytest.fixture
    def mock_oracle_config(self) -> FlextDbOracleConfig: ...
    @pytest.fixture
    def mock_connection(self, mock_oracle_config: FlextDbOracleConfig) -> MagicMock: ...
    def test_api_full_workflow(
        self, mock_oracle_config: FlextDbOracleConfig, mock_connection: MagicMock
    ) -> None: ...
    def test_connection_error_handling(
        self, mock_oracle_config: FlextDbOracleConfig
    ) -> None: ...
    def test_transaction_context_manager(
        self, mock_oracle_config: FlextDbOracleConfig, mock_connection: MagicMock
    ) -> None: ...
    def test_batch_operations(
        self, mock_oracle_config: FlextDbOracleConfig, mock_connection: MagicMock
    ) -> None: ...
    def test_metadata_operations(
        self, mock_oracle_config: FlextDbOracleConfig, mock_connection: MagicMock
    ) -> None: ...
    def test_configuration_from_environment(self) -> None: ...
    def test_api_factory_methods(self) -> None: ...
    def test_connection_retry_mechanism(
        self, mock_oracle_config: FlextDbOracleConfig
    ) -> None: ...
    def test_context_manager_integration(
        self, mock_oracle_config: FlextDbOracleConfig, mock_connection: MagicMock
    ) -> None: ...
    def test_singer_type_conversion_integration(
        self, mock_oracle_config: FlextDbOracleConfig, mock_connection: MagicMock
    ) -> None: ...
    def test_ddl_generation_integration(
        self, mock_oracle_config: FlextDbOracleConfig, mock_connection: MagicMock
    ) -> None: ...
