from flext_db_oracle import FlextDbOracleApi, FlextDbOracleConfig

class TestRealOracleExceptionsCore:
    def test_real_authentication_error_scenario(self) -> None: ...
    def test_real_connection_error_scenario(self) -> None: ...
    def test_real_configuration_error_scenario(self) -> None: ...
    def test_real_query_error_scenario(
        self, real_oracle_config: FlextDbOracleConfig
    ) -> None: ...
    def test_real_timeout_error_scenario(
        self, real_oracle_config: FlextDbOracleConfig
    ) -> None: ...

class TestRealOracleExceptionsAdvanced:
    def test_real_metadata_error_scenario(
        self, connected_oracle_api: FlextDbOracleApi
    ) -> None: ...
    def test_real_processing_error_scenario(
        self, connected_oracle_api: FlextDbOracleApi
    ) -> None: ...
    def test_real_validation_error_scenario(self) -> None: ...

class TestRealOracleExceptionHierarchy:
    def test_real_exception_inheritance(self) -> None: ...
    def test_real_exception_instantiation(self) -> None: ...
    def test_real_exception_context_handling(self) -> None: ...
