class TestTypesValidationMethods:
    def test_column_validation_methods_lines_120_132(self) -> None: ...
    def test_table_validation_methods_lines_175_187(self) -> None: ...
    def test_validation_error_handling_lines_131_132_186_187(self) -> None: ...

class TestTypesPropertyMethods:
    def test_column_property_methods_lines_191_200(self) -> None: ...
    def test_table_property_methods_lines_204_208(self) -> None: ...

class TestTypesUtilityFunctions:
    def test_types_utility_functions_comprehensive(self) -> None: ...
    def test_edge_case_validation_scenarios(self) -> None: ...
