from flext_db_oracle import FlextDbOracleApi, FlextDbOracleConfig

class TestRealOraclePlugins:
    def test_real_plugins_create_performance(self, oracle_container: None) -> None: ...
    def test_real_plugins_create_security(self, oracle_container: None) -> None: ...
    def test_real_plugins_create_validation(self, oracle_container: None) -> None: ...
    def test_real_plugins_register_all(
        self, oracle_api: FlextDbOracleApi, oracle_container: None
    ) -> None: ...

class TestRealOraclePluginErrorHandling:
    def test_real_plugins_create_all_types(self) -> None: ...
    def test_real_plugins_register_with_empty_dict(
        self, oracle_api: FlextDbOracleApi, oracle_container: None
    ) -> None: ...
    def test_real_plugins_register_multiple_times(
        self, real_oracle_config: FlextDbOracleConfig, oracle_container: None
    ) -> None: ...

class TestRealOraclePluginIntegration:
    def test_real_plugins_with_oracle_metadata(
        self, oracle_api: FlextDbOracleApi, oracle_container: None
    ) -> None: ...
    def test_real_plugins_with_oracle_connection(
        self, oracle_api: FlextDbOracleApi, oracle_container: None
    ) -> None: ...
    def test_real_plugins_with_query_operations(
        self, oracle_api: FlextDbOracleApi, oracle_container: None
    ) -> None: ...
    def test_real_plugins_comprehensive_coverage(
        self, oracle_api: FlextDbOracleApi, oracle_container: None
    ) -> None: ...
    def test_real_plugins_plugin_object_types(self) -> None: ...
    def test_real_plugins_with_different_configs(
        self, real_oracle_config: FlextDbOracleConfig, oracle_container: None
    ) -> None: ...
