import pytest
from click.testing import CliRunner

class TestRealOracleCli:
    @pytest.fixture
    def cli_runner(self) -> CliRunner: ...
    def test_real_cli_connect_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_query_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_schemas_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_tables_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_health_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_tables_schema_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_optimize_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_plugins_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...

class TestRealOracleCliErrorHandling:
    @pytest.fixture
    def cli_runner(self) -> CliRunner: ...
    def test_real_cli_invalid_sql_query(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_invalid_table_name(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_help_command(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_verbose_debug_mode(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_json_output(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_yaml_output(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_csv_output(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...

class TestRealOracleCliCoverageBoost:
    @pytest.fixture
    def cli_runner(self) -> CliRunner: ...
    def test_real_cli_connection_parameters_processing(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_error_handling_paths(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_interactive_commands(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_advanced_output_formatting(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
    def test_real_cli_all_commands_coverage(
        self, cli_runner: CliRunner, oracle_container: None
    ) -> None: ...
