from flext_db_oracle import FlextDbOracleConfig

class TestAPIMissedLines:
    def test_api_error_handling_methods_107_109(
        self, oracle_api: object, oracle_container: object
    ) -> None: ...
    def test_api_connection_manager_lines_117_133(
        self, real_oracle_config: object, oracle_container: object
    ) -> None: ...
    def test_api_query_operations_571_610(
        self, oracle_api: object, oracle_container: object
    ) -> None: ...
    def test_api_schema_operations_1038_1058(
        self, oracle_api: object, oracle_container: object
    ) -> None: ...

class TestConnectionMissedLines:
    def test_connection_error_paths_73_77(
        self, real_oracle_config: FlextDbOracleConfig
    ) -> None: ...
    def test_connection_lifecycle_140_147(
        self, real_oracle_config: FlextDbOracleConfig
    ) -> None: ...

class TestTypesMissedLines:
    def test_types_validation_lines_120_132(self) -> None: ...
    def test_types_property_methods_175_187(self) -> None: ...

class TestPluginsMissedLines:
    def test_plugins_validation_functions_69_83(self) -> None: ...
    def test_plugins_business_rules_91_103(self) -> None: ...
    def test_plugins_creation_functions_223_241(self) -> None: ...

class TestCLIMissedLines:
    def test_cli_parameter_processing_267_274(self) -> None: ...
    def test_cli_output_formatting_721_769(self) -> None: ...
