# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Tests package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_core.typings import FlextTypes

    from flext_db_oracle import d, e, h, r, s, x

    from . import e2e as e2e, integration as integration, unit as unit
    from .conftest import (
        OperationTestError,
        connected_oracle_api,
        docker_control,
        ensure_shared_docker_container,
        flext_domains,
        logger,
        mock_oracle_config,
        oracle_api,
        oracle_available,
        oracle_config,
        oracle_container,
        pytest_configure,
        pytest_runtest_makereport,
        pytest_sessionstart,
        real_oracle_config,
        shared_oracle_container,
        test_cleanup,
        test_database_setup,
    )
    from .constants import TestsFlextDbOracleConstants, TestsFlextDbOracleConstants as c
    from .e2e import TestOracleE2E
    from .integration import TestOracleIntegration
    from .models import TestsFlextDbOracleModels, TestsFlextDbOracleModels as m, tm
    from .protocols import TestsFlextDbOracleProtocols, TestsFlextDbOracleProtocols as p
    from .typings import TestsFlextDbOracleTypes, TestsFlextDbOracleTypes as t
    from .unit import (
        TestApiModule,
        TestApiSurgicalSimple,
        TestBasicModelCreation,
        TestCLIRealFunctionality,
        TestCliServiceOperations,
        TestConstants,
        TestDirectCoverageBoostAPI,
        TestDirectCoverageBoostConfig,
        TestDirectCoverageBoostConnection,
        TestDirectCoverageBoostObservability,
        TestDirectCoverageBoostServices,
        TestDirectCoverageBoostTypes,
        TestDispatcherSurgical,
        TestExceptions,
        TestFlextDbOracleApiRealFunctionality,
        TestFlextDbOracleApiSafeMethods,
        TestFlextDbOracleApiWorking,
        TestFlextDbOracleCli,
        TestFlextDbOracleClientIntegration,
        TestFlextDbOracleClientReal,
        TestFlextDbOracleClientRealFunctionality,
        TestFlextDbOracleConnectionSimple,
        TestFlextDbOracleConstants,
        TestFlextDbOracleExceptions,
        TestFlextDbOracleFields,
        TestFlextDbOracleMetadataManagerComprehensive,
        TestFlextDbOracleModels,
        TestFlextDbOracleProtocols,
        TestFlextDbOracleServices,
        TestFlextDbOracleServicesBasic,
        TestFlextDbOracleServicesPlaceholderRemovals,
        TestFlextDbOracleSettings,
        TestFlextDbOracleTypes,
        TestFlextDbOracleUtilities,
        TestModuleImports,
        TestOracleConnectionHelper,
        TestOutputFormatter,
        TestRealOracleApi,
        TestRealOracleConnection,
        TestRealOracleErrorHandling,
        TestRealOracleExceptionHierarchy,
        TestRealOracleExceptionsAdvanced,
        TestRealOracleExceptionsCore,
        TestServiceErrorHandling,
        TestUtilities,
        TestYamlModule,
        safe_get_first_value,
    )
    from .utilities import TestsFlextDbOracleUtilities, TestsFlextDbOracleUtilities as u

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "OperationTestError": ("tests.conftest", "OperationTestError"),
    "TestApiModule": ("tests.unit", "TestApiModule"),
    "TestApiSurgicalSimple": ("tests.unit", "TestApiSurgicalSimple"),
    "TestBasicModelCreation": ("tests.unit", "TestBasicModelCreation"),
    "TestCLIRealFunctionality": ("tests.unit", "TestCLIRealFunctionality"),
    "TestCliServiceOperations": ("tests.unit", "TestCliServiceOperations"),
    "TestConstants": ("tests.unit", "TestConstants"),
    "TestDirectCoverageBoostAPI": ("tests.unit", "TestDirectCoverageBoostAPI"),
    "TestDirectCoverageBoostConfig": ("tests.unit", "TestDirectCoverageBoostConfig"),
    "TestDirectCoverageBoostConnection": (
        "tests.unit",
        "TestDirectCoverageBoostConnection",
    ),
    "TestDirectCoverageBoostObservability": (
        "tests.unit",
        "TestDirectCoverageBoostObservability",
    ),
    "TestDirectCoverageBoostServices": (
        "tests.unit",
        "TestDirectCoverageBoostServices",
    ),
    "TestDirectCoverageBoostTypes": ("tests.unit", "TestDirectCoverageBoostTypes"),
    "TestDispatcherSurgical": ("tests.unit", "TestDispatcherSurgical"),
    "TestExceptions": ("tests.unit", "TestExceptions"),
    "TestFlextDbOracleApiRealFunctionality": (
        "tests.unit",
        "TestFlextDbOracleApiRealFunctionality",
    ),
    "TestFlextDbOracleApiSafeMethods": (
        "tests.unit",
        "TestFlextDbOracleApiSafeMethods",
    ),
    "TestFlextDbOracleApiWorking": ("tests.unit", "TestFlextDbOracleApiWorking"),
    "TestFlextDbOracleCli": ("tests.unit", "TestFlextDbOracleCli"),
    "TestFlextDbOracleClientIntegration": (
        "tests.unit",
        "TestFlextDbOracleClientIntegration",
    ),
    "TestFlextDbOracleClientReal": ("tests.unit", "TestFlextDbOracleClientReal"),
    "TestFlextDbOracleClientRealFunctionality": (
        "tests.unit",
        "TestFlextDbOracleClientRealFunctionality",
    ),
    "TestFlextDbOracleConnectionSimple": (
        "tests.unit",
        "TestFlextDbOracleConnectionSimple",
    ),
    "TestFlextDbOracleConstants": ("tests.unit", "TestFlextDbOracleConstants"),
    "TestFlextDbOracleExceptions": ("tests.unit", "TestFlextDbOracleExceptions"),
    "TestFlextDbOracleFields": ("tests.unit", "TestFlextDbOracleFields"),
    "TestFlextDbOracleMetadataManagerComprehensive": (
        "tests.unit",
        "TestFlextDbOracleMetadataManagerComprehensive",
    ),
    "TestFlextDbOracleModels": ("tests.unit", "TestFlextDbOracleModels"),
    "TestFlextDbOracleProtocols": ("tests.unit", "TestFlextDbOracleProtocols"),
    "TestFlextDbOracleServices": ("tests.unit", "TestFlextDbOracleServices"),
    "TestFlextDbOracleServicesBasic": ("tests.unit", "TestFlextDbOracleServicesBasic"),
    "TestFlextDbOracleServicesPlaceholderRemovals": (
        "tests.unit",
        "TestFlextDbOracleServicesPlaceholderRemovals",
    ),
    "TestFlextDbOracleSettings": ("tests.unit", "TestFlextDbOracleSettings"),
    "TestFlextDbOracleTypes": ("tests.unit", "TestFlextDbOracleTypes"),
    "TestFlextDbOracleUtilities": ("tests.unit", "TestFlextDbOracleUtilities"),
    "TestModuleImports": ("tests.unit", "TestModuleImports"),
    "TestOracleConnectionHelper": ("tests.unit", "TestOracleConnectionHelper"),
    "TestOracleE2E": ("tests.e2e", "TestOracleE2E"),
    "TestOracleIntegration": ("tests.integration", "TestOracleIntegration"),
    "TestOutputFormatter": ("tests.unit", "TestOutputFormatter"),
    "TestRealOracleApi": ("tests.unit", "TestRealOracleApi"),
    "TestRealOracleConnection": ("tests.unit", "TestRealOracleConnection"),
    "TestRealOracleErrorHandling": ("tests.unit", "TestRealOracleErrorHandling"),
    "TestRealOracleExceptionHierarchy": (
        "tests.unit",
        "TestRealOracleExceptionHierarchy",
    ),
    "TestRealOracleExceptionsAdvanced": (
        "tests.unit",
        "TestRealOracleExceptionsAdvanced",
    ),
    "TestRealOracleExceptionsCore": ("tests.unit", "TestRealOracleExceptionsCore"),
    "TestServiceErrorHandling": ("tests.unit", "TestServiceErrorHandling"),
    "TestUtilities": ("tests.unit", "TestUtilities"),
    "TestYamlModule": ("tests.unit", "TestYamlModule"),
    "TestsFlextDbOracleConstants": ("tests.constants", "TestsFlextDbOracleConstants"),
    "TestsFlextDbOracleModels": ("tests.models", "TestsFlextDbOracleModels"),
    "TestsFlextDbOracleProtocols": ("tests.protocols", "TestsFlextDbOracleProtocols"),
    "TestsFlextDbOracleTypes": ("tests.typings", "TestsFlextDbOracleTypes"),
    "TestsFlextDbOracleUtilities": ("tests.utilities", "TestsFlextDbOracleUtilities"),
    "c": ("tests.constants", "TestsFlextDbOracleConstants"),
    "connected_oracle_api": ("tests.conftest", "connected_oracle_api"),
    "d": ("flext_db_oracle", "d"),
    "docker_control": ("tests.conftest", "docker_control"),
    "e": ("flext_db_oracle", "e"),
    "e2e": ("tests.e2e", ""),
    "ensure_shared_docker_container": (
        "tests.conftest",
        "ensure_shared_docker_container",
    ),
    "flext_domains": ("tests.conftest", "flext_domains"),
    "h": ("flext_db_oracle", "h"),
    "integration": ("tests.integration", ""),
    "logger": ("tests.conftest", "logger"),
    "m": ("tests.models", "TestsFlextDbOracleModels"),
    "mock_oracle_config": ("tests.conftest", "mock_oracle_config"),
    "oracle_api": ("tests.conftest", "oracle_api"),
    "oracle_available": ("tests.conftest", "oracle_available"),
    "oracle_config": ("tests.conftest", "oracle_config"),
    "oracle_container": ("tests.conftest", "oracle_container"),
    "p": ("tests.protocols", "TestsFlextDbOracleProtocols"),
    "pytest_configure": ("tests.conftest", "pytest_configure"),
    "pytest_runtest_makereport": ("tests.conftest", "pytest_runtest_makereport"),
    "pytest_sessionstart": ("tests.conftest", "pytest_sessionstart"),
    "r": ("flext_db_oracle", "r"),
    "real_oracle_config": ("tests.conftest", "real_oracle_config"),
    "s": ("flext_db_oracle", "s"),
    "safe_get_first_value": ("tests.unit", "safe_get_first_value"),
    "shared_oracle_container": ("tests.conftest", "shared_oracle_container"),
    "t": ("tests.typings", "TestsFlextDbOracleTypes"),
    "test_cleanup": ("tests.conftest", "test_cleanup"),
    "test_database_setup": ("tests.conftest", "test_database_setup"),
    "tm": ("tests.models", "tm"),
    "u": ("tests.utilities", "TestsFlextDbOracleUtilities"),
    "unit": ("tests.unit", ""),
    "x": ("flext_db_oracle", "x"),
}

__all__ = [
    "OperationTestError",
    "TestApiModule",
    "TestApiSurgicalSimple",
    "TestBasicModelCreation",
    "TestCLIRealFunctionality",
    "TestCliServiceOperations",
    "TestConstants",
    "TestDirectCoverageBoostAPI",
    "TestDirectCoverageBoostConfig",
    "TestDirectCoverageBoostConnection",
    "TestDirectCoverageBoostObservability",
    "TestDirectCoverageBoostServices",
    "TestDirectCoverageBoostTypes",
    "TestDispatcherSurgical",
    "TestExceptions",
    "TestFlextDbOracleApiRealFunctionality",
    "TestFlextDbOracleApiSafeMethods",
    "TestFlextDbOracleApiWorking",
    "TestFlextDbOracleCli",
    "TestFlextDbOracleClientIntegration",
    "TestFlextDbOracleClientReal",
    "TestFlextDbOracleClientRealFunctionality",
    "TestFlextDbOracleConnectionSimple",
    "TestFlextDbOracleConstants",
    "TestFlextDbOracleExceptions",
    "TestFlextDbOracleFields",
    "TestFlextDbOracleMetadataManagerComprehensive",
    "TestFlextDbOracleModels",
    "TestFlextDbOracleProtocols",
    "TestFlextDbOracleServices",
    "TestFlextDbOracleServicesBasic",
    "TestFlextDbOracleServicesPlaceholderRemovals",
    "TestFlextDbOracleSettings",
    "TestFlextDbOracleTypes",
    "TestFlextDbOracleUtilities",
    "TestModuleImports",
    "TestOracleConnectionHelper",
    "TestOracleE2E",
    "TestOracleIntegration",
    "TestOutputFormatter",
    "TestRealOracleApi",
    "TestRealOracleConnection",
    "TestRealOracleErrorHandling",
    "TestRealOracleExceptionHierarchy",
    "TestRealOracleExceptionsAdvanced",
    "TestRealOracleExceptionsCore",
    "TestServiceErrorHandling",
    "TestUtilities",
    "TestYamlModule",
    "TestsFlextDbOracleConstants",
    "TestsFlextDbOracleModels",
    "TestsFlextDbOracleProtocols",
    "TestsFlextDbOracleTypes",
    "TestsFlextDbOracleUtilities",
    "c",
    "connected_oracle_api",
    "d",
    "docker_control",
    "e",
    "e2e",
    "ensure_shared_docker_container",
    "flext_domains",
    "h",
    "integration",
    "logger",
    "m",
    "mock_oracle_config",
    "oracle_api",
    "oracle_available",
    "oracle_config",
    "oracle_container",
    "p",
    "pytest_configure",
    "pytest_runtest_makereport",
    "pytest_sessionstart",
    "r",
    "real_oracle_config",
    "s",
    "safe_get_first_value",
    "shared_oracle_container",
    "t",
    "test_cleanup",
    "test_database_setup",
    "tm",
    "u",
    "unit",
    "x",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
