"""Oracle Database exceptions using FLEXT ecosystem patterns.

All Oracle-specific exceptions are automatically generated by flext-core.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from flext_core import FlextExceptions, FlextTypes


class FlextDbOracleExceptions:
    """Unified Oracle Database Exception System using flext-core exclusively.

    NO LOCAL IMPLEMENTATIONS - everything delegates to flext-core.
    Uses FlextExceptions.create_module_exception_classes for automatic generation.
    """

    # Generate all Oracle exception classes using flext-core
    _oracle_exceptions = FlextExceptions.create_module_exception_classes(
        "FLEXT_DB_ORACLE"
    )

    # Direct access to all generated exception classes
    BaseError = _oracle_exceptions["FLEXT_DB_ORACLEBaseError"]
    ValidationError = _oracle_exceptions["FLEXT_DB_ORACLEValidationError"]
    ConfigurationError = _oracle_exceptions["FLEXT_DB_ORACLEConfigurationError"]
    ConnectionError = _oracle_exceptions["FLEXT_DB_ORACLEConnectionError"]
    AuthenticationError = _oracle_exceptions["FLEXT_DB_ORACLEAuthenticationError"]
    ProcessingError = _oracle_exceptions["FLEXT_DB_ORACLEProcessingError"]
    TimeoutError = _oracle_exceptions["FLEXT_DB_ORACLETimeoutError"]

    # Additional Oracle-specific aliases using existing base classes
    DatabaseConnectionError = ConnectionError
    QueryError = ProcessingError
    MetadataError = ProcessingError

    @classmethod
    def create_validation_error(
        cls, message: str, context: FlextTypes.Core.Dict | None = None
    ) -> Exception:
        """Factory method for validation errors using flext-core."""
        return cls.ValidationError(message, context=context)

    @classmethod
    def create_connection_error(
        cls, message: str, context: FlextTypes.Core.Dict | None = None
    ) -> Exception:
        """Factory method for connection errors using flext-core."""
        return cls.ConnectionError(message, context=context)

    @classmethod
    def is_oracle_error(cls, error: Exception) -> bool:
        """Check if exception is an Oracle database error using flext-core."""
        return isinstance(error, cls.BaseError)


# Module-level aliases for backward compatibility - direct references to flext-core generated classes
OracleConnectionError = FlextDbOracleExceptions.DatabaseConnectionError
OracleQueryError = FlextDbOracleExceptions.QueryError
OracleValidationError = FlextDbOracleExceptions.ValidationError

__all__: FlextTypes.Core.StringList = [
    "FlextDbOracleExceptions",
    "OracleConnectionError",
    "OracleQueryError",
    "OracleValidationError",
]
