MAX_OUTPUT_LINES: int

def run_cli_command(cmd: list[str]) -> tuple[int, str, str]: ...
def demo_cli_commands() -> None: ...
def show_environment_setup() -> None: ...
def show_docker_example() -> None: ...
def main() -> None: ...
