from _typeshed import Incomplete

from flext_db_oracle import FlextDbOracleApi, FlextDbOracleConfig

logger: Incomplete

def create_sample_config() -> FlextDbOracleConfig: ...

class OracleExampleDemonstrator:
    context_name: Incomplete
    log_emoji: Incomplete
    log_message: Incomplete
    api: Incomplete
    def __init__(self, context_name: str, log_emoji: str, log_message: str) -> None: ...
    def demonstrate_info_patterns(
        self, patterns: list[tuple[str, list[str]]]
    ) -> None: ...
    def demonstrate_with_api_operations(self, operation_func: object) -> None: ...

def demonstrate_connection_patterns() -> None: ...
def demonstrate_configuration_patterns() -> None: ...
def demonstrate_query_patterns() -> None: ...
def demonstrate_metadata_exploration() -> None: ...
def demonstrate_transaction_patterns() -> None: ...
def demonstrate_error_handling_patterns() -> None: ...
def demonstrate_fallback_operations(api: FlextDbOracleApi) -> str: ...
def create_pattern_config(
    name: str, emoji: str, patterns: list[tuple[str, list[str]]]
) -> dict[str, object]: ...

PERFORMANCE_PATTERNS: Incomplete
MONITORING_PATTERNS: Incomplete
PATTERN_CONFIGURATIONS: Incomplete

def demonstrate_performance_patterns() -> None: ...
def demonstrate_monitoring_patterns() -> None: ...
def demonstrate_integration_patterns() -> None: ...
async def demonstrate_async_patterns() -> None: ...
def main() -> None: ...
