from collections.abc import Iterator
from contextlib import contextmanager

from sqlalchemy import Engine as Engine

from flext_db_oracle import FlextDbOracleConfig

def create_oracle_config() -> FlextDbOracleConfig: ...
@contextmanager
def oracle_connection() -> Iterator[Engine]: ...
def demonstrate_basic_queries() -> None: ...
def demonstrate_table_operations() -> None: ...
def demonstrate_metadata_introspection() -> None: ...
def demonstrate_transaction_management() -> None: ...
def main() -> None: ...
