from collections.abc import Generator
from pathlib import Path

import pytest
from _typeshed import Incomplete

from flext_db_oracle import FlextDbOracleApi, FlextDbOracleConfig

class DockerCommandExecutor:
    compose_file: Incomplete
    def __init__(self, compose_file: Path) -> None: ...
    def check_docker_availability(self) -> None: ...
    def check_container_status(self) -> bool: ...
    def check_container_health(self) -> bool: ...
    def start_container(self) -> None: ...
    def run_setup_script(self) -> bool: ...
    def is_setup_completed(self) -> bool: ...

class OracleContainerManager:
    docker_executor: Incomplete
    max_health_attempts: int
    health_check_interval: int
    def __init__(self, compose_file: Path) -> None: ...
    def ensure_container_ready(self) -> None: ...

def pytest_configure(config: pytest.Config) -> None: ...
def oracle_container() -> Generator[None]: ...
@pytest.fixture
def real_oracle_config(oracle_container: None) -> FlextDbOracleConfig: ...
@pytest.fixture
def oracle_api(real_oracle_config: FlextDbOracleConfig) -> FlextDbOracleApi: ...
@pytest.fixture
def connected_oracle_api(
    oracle_api: FlextDbOracleApi,
) -> Generator[FlextDbOracleApi]: ...
