import types
from typing import Self, TypeVar

from _typeshed import Incomplete
from flext_core import FlextPlugin, FlextResult
from flext_observability import FlextHealthCheck

from flext_db_oracle.config import FlextDbOracleConfig
from flext_db_oracle.config_types import MergeStatementConfig
from flext_db_oracle.connection import CreateIndexConfig, FlextDbOracleConnection
from flext_db_oracle.observability import FlextDbOracleObservabilityManager
from flext_db_oracle.typings import TDbOracleQueryResult

__all__ = [
    "FlextDbOracleApi",
    "OracleConnectionManager",
    "OracleQueryExecutor",
    "create_oracle_api",
    "create_oracle_api_from_env",
]

T = TypeVar("T")

class OracleConnectionManager:
    def __init__(
        self,
        config: FlextDbOracleConfig,
        observability: FlextDbOracleObservabilityManager | None,
        context_name: str,
        retry_attempts: int = 3,
    ) -> None: ...
    @property
    def is_connected(self) -> bool: ...
    @property
    def connection(self) -> FlextDbOracleConnection | None: ...
    def connect(self) -> FlextResult[None]: ...
    def disconnect(self) -> FlextResult[None]: ...
    def test_connection(self) -> FlextResult[bool]: ...

class ApiResponseFormatter:
    def __init__(self, logger: object) -> None: ...
    def format_health_status(self, health_check: object) -> dict[str, object]: ...
    def create_connection_status(
        self,
        *,
        connected: bool,
        query_success: bool,
        observability_active: bool,
        error: str | None = None,
    ) -> dict[str, object]: ...

class ApiPluginManager:
    def __init__(self, plugins: dict[str, object], plugin_platform: object) -> None: ...
    def try_get_complex_plugin(
        self, plugin_name: str
    ) -> FlextResult[object] | None: ...
    def get_simple_plugin(self, plugin_name: str) -> FlextResult[object]: ...
    def try_list_complex_plugins(self) -> FlextResult[list[object]] | None: ...
    def register_plugin_simple(self, plugin: object) -> str: ...
    def try_register_complex_plugin(
        self, plugin: object
    ) -> FlextResult[None] | None: ...
    def list_simple_plugins(self) -> FlextResult[list[object]]: ...

class ApiConnectionValidator:
    def __init__(self, logger: object) -> None: ...
    def validate_connection_manager(
        self, connection_manager: object | None, operation: str
    ) -> FlextResult[None]: ...
    def validate_connection_active(
        self, connection_manager: object, operation: str
    ) -> FlextResult[None]: ...
    def validate_query_executor(
        self, query_executor: object | None, operation: str
    ) -> FlextResult[None]: ...

class OracleQueryExecutor:
    def __init__(
        self,
        connection_manager: OracleConnectionManager,
        observability: FlextDbOracleObservabilityManager | None,
        context_name: str,
    ) -> None: ...
    def execute_query(
        self, sql: str, params: dict[str, object] | None = None
    ) -> FlextResult[TDbOracleQueryResult]: ...
    def execute_query_single(
        self, sql: str, params: dict[str, object] | None = None
    ) -> FlextResult[dict[str, object] | None]: ...
    def execute_batch(
        self,
        operations: list[tuple[str, dict[str, object] | None]]
        | list[tuple[str, object]],
    ) -> FlextResult[list[TDbOracleQueryResult]]: ...

class FlextDbOracleApi:
    def __init__(
        self, config: FlextDbOracleConfig | None = None, context_name: str = "oracle"
    ) -> None: ...
    @classmethod
    def from_env(
        cls, env_prefix: str = "FLEXT_TARGET_ORACLE", context_name: str = "oracle"
    ) -> Self: ...
    @classmethod
    def from_config(cls, config: object) -> Self: ...
    @classmethod
    def with_config(
        cls,
        config_dict: dict[str, object] | FlextDbOracleConfig | None = None,
        context_name: str = "oracle",
        **kwargs: object,
    ) -> Self: ...
    @classmethod
    def from_url(cls, url: str, context_name: str = "oracle") -> Self: ...
    def connect(self) -> Self: ...
    def disconnect(self) -> Self: ...
    def test_connection(self) -> FlextResult[bool]: ...
    def test_connection_with_observability(self) -> FlextResult[dict[str, object]]: ...
    @property
    def config(self) -> FlextDbOracleConfig | None: ...
    @property
    def connection(self) -> FlextDbOracleConnection | None: ...
    @property
    def is_connected(self) -> bool: ...
    def query(
        self, sql: str, params: dict[str, object] | None = None
    ) -> FlextResult[TDbOracleQueryResult]: ...
    def query_one(
        self, sql: str, params: dict[str, object] | None = None
    ) -> FlextResult[tuple[object, ...] | None]: ...
    def execute_batch(
        self, operations: list[tuple[str, dict[str, object] | None]]
    ) -> FlextResult[list[TDbOracleQueryResult]]: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...
    def transaction(self) -> _TransactionContextManager: ...
    def get_health_check(self) -> FlextResult[FlextHealthCheck]: ...
    def register_plugin(self, plugin: FlextPlugin) -> FlextResult[None]: ...
    def unregister_plugin(self, plugin_name: str) -> FlextResult[None]: ...
    def get_plugin(self, plugin_name: str) -> FlextResult[FlextPlugin]: ...
    def execute_plugin(
        self, plugin_name: str, **kwargs: dict[str, object]
    ) -> FlextResult[dict[str, object]]: ...
    def list_plugins(self) -> FlextResult[list[FlextPlugin]]: ...
    def query_with_timing(
        self, sql: str, params: dict[str, object] | None = None
    ) -> FlextResult[TDbOracleQueryResult]: ...
    def get_schemas(self) -> FlextResult[list[str]]: ...
    def get_tables(self, schema: str | None = None) -> FlextResult[list[str]]: ...
    def get_columns(
        self, table_name: str, schema: str | None = None
    ) -> FlextResult[list[dict[str, object]]]: ...
    def optimize_query(self, sql: str) -> FlextResult[dict[str, object]]: ...
    def get_health_status(self) -> FlextResult[dict[str, object]]: ...
    def build_select(
        self,
        table_name: str,
        columns: list[str] | None = None,
        conditions: dict[str, object] | None = None,
        schema: str | None = None,
    ) -> FlextResult[str]: ...
    def map_singer_schema(
        self, singer_schema: dict[str, object]
    ) -> FlextResult[dict[str, object]]: ...
    def get_primary_keys(
        self, table_name: str, schema: str | None = None
    ) -> FlextResult[list[str]]: ...
    def get_observability_metrics(self) -> FlextResult[dict[str, object]]: ...
    def execute_connection_monitor(
        self, **kwargs: dict[str, object]
    ) -> FlextResult[dict[str, object]]: ...
    def create_table_ddl(
        self,
        table_name: str,
        columns: list[dict[str, object]],
        schema: str | None = None,
    ) -> FlextResult[str]: ...
    def drop_table_ddl(
        self, table_name: str, schema: str | None = None
    ) -> FlextResult[str]: ...
    def get_table_metadata(
        self, table_name: str, schema: str | None = None
    ) -> FlextResult[dict[str, object]]: ...
    def convert_singer_type(
        self, singer_type: str | list[str], format_hint: str | None = None
    ) -> FlextResult[str]: ...
    def execute_ddl(self, sql: str) -> FlextResult[None]: ...
    def build_insert_statement(
        self,
        table_name: str,
        columns: list[str],
        schema_name: str | None = None,
        returning_columns: list[str] | None = None,
        hints: list[str] | None = None,
    ) -> FlextResult[str]: ...
    def build_update_statement(
        self,
        table_name: str,
        set_columns: list[str],
        where_columns: list[str],
        schema_name: str | None = None,
        returning_columns: list[str] | None = None,
    ) -> FlextResult[str]: ...
    def build_merge_statement(
        self, config: MergeStatementConfig
    ) -> FlextResult[str]: ...
    def build_delete_statement(
        self, table_name: str, where_columns: list[str], schema_name: str | None = None
    ) -> FlextResult[str]: ...
    def build_create_index_statement(
        self, config: CreateIndexConfig
    ) -> FlextResult[str]: ...

class _TransactionContextManager:
    api: Incomplete
    connection: Incomplete
    def __init__(
        self, api: FlextDbOracleApi, connection: FlextDbOracleConnection
    ) -> None: ...
    def __enter__(self) -> FlextDbOracleApi: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...

def create_oracle_api(
    config: FlextDbOracleConfig | None = None, context_name: str = "oracle"
) -> FlextDbOracleApi: ...
def create_oracle_api_from_env(
    env_prefix: str = "FLEXT_TARGET_ORACLE_", context_name: str = "oracle"
) -> FlextDbOracleApi: ...
