from dataclasses import dataclass

__all__ = ["CreateIndexStatementConfig", "MergeStatementConfig"]

@dataclass
class MergeStatementConfig:
    target_table: str
    source_columns: list[str]
    merge_keys: list[str]
    update_columns: list[str] | None = ...
    insert_columns: list[str] | None = ...
    schema_name: str | None = ...
    hints: list[str] | None = ...

@dataclass
class CreateIndexStatementConfig:
    index_name: str
    table_name: str
    columns: list[str]
    unique: bool = ...
    schema_name: str | None = ...
    tablespace: str | None = ...
    parallel: int | None = ...
