
from flext_core import FlextResult
from flext_core.config import FlextOracleConfig
from pydantic import SecretStr

__all__ = ["FlextDbOracleConfig"]

class FlextDbOracleConfig(FlextOracleConfig):
    ssl_enabled: bool
    ssl_cert_path: str | None
    ssl_key_path: str | None
    ssl_server_dn_match: bool
    ssl_server_cert_dn: str | None
    timeout: int
    encoding: str
    protocol: str
    pool_increment: int
    autocommit: bool
    password: SecretStr
    @classmethod
    def validate_host_not_empty(cls, v: str) -> str: ...
    @classmethod
    def validate_username_not_empty(cls, v: str) -> str: ...
    @classmethod
    def validate_port_range(cls, v: int) -> int: ...
    @classmethod
    def validate_timeout(cls, v: int) -> int: ...
    @classmethod
    def validate_encoding(cls, v: str) -> str: ...
    @classmethod
    def validate_protocol(cls, v: str) -> str: ...
    @classmethod
    def coerce_password(cls, v: object) -> SecretStr: ...
    @classmethod
    def validate_oracle_schema(cls, v: str) -> str: ...
    def validate_pool_settings(self) -> FlextDbOracleConfig: ...
    def validate_connection_identifiers(self) -> FlextDbOracleConfig: ...
    def validate_ssl_settings(self) -> FlextDbOracleConfig: ...
    def validate_business_rules(self) -> FlextResult[None]: ...
    @classmethod
    def from_env(cls, prefix: str = "FLEXT_TARGET_ORACLE") -> FlextDbOracleConfig: ...
    @property
    def success(self) -> bool: ...
    @property
    def is_failure(self) -> bool: ...
    @property
    def data(self) -> FlextDbOracleConfig: ...
    @property
    def error(self) -> str | None: ...
    @classmethod
    def from_env_with_result(
        cls, prefix: str = "FLEXT_TARGET_ORACLE_"
    ) -> FlextResult[FlextDbOracleConfig]: ...
    @classmethod
    def from_url(cls, url: str) -> FlextResult[FlextDbOracleConfig]: ...
    def to_connect_params(self) -> dict[str, object]: ...
    def to_pool_params(self) -> dict[str, object]: ...
    def get_connection_string(self) -> str: ...
    @classmethod
    def from_dict(cls, data: dict[str, object]) -> FlextDbOracleConfig: ...
    @classmethod
    def from_dict_with_result(
        cls, config_dict: dict[str, object]
    ) -> FlextResult[FlextDbOracleConfig]: ...
