from datetime import datetime
from typing import ClassVar

from _typeshed import Incomplete
from flext_core import FlextResult, FlextValueObject

from flext_db_oracle.connection import FlextDbOracleConnection

__all__ = [
    "FlextDbOracleColumn",
    "FlextDbOracleMetadataManager",
    "FlextDbOracleSchema",
    "FlextDbOracleTable",
]

class ValidationMixin: ...

class FlextDbOracleColumn(ValidationMixin, FlextValueObject):
    model_config: ClassVar[Incomplete]
    name: str
    data_type: str
    nullable: bool
    is_primary_key: bool
    default_value: str | None
    data_length: int | None
    data_precision: int | None
    data_scale: int | None
    column_id: int
    comments: str | None
    def validate_business_rules(self) -> FlextResult[None]: ...
    def validate_domain_rules(self) -> FlextResult[None]: ...
    @property
    def full_type_definition(self) -> str: ...
    @property
    def full_type_spec(self) -> str: ...
    @property
    def is_key_column(self) -> bool: ...

class FlextDbOracleTable(ValidationMixin, FlextValueObject):
    name: str
    schema_name: str
    columns: list[FlextDbOracleColumn]
    row_count: int | None
    size_mb: float | None
    comments: str | None
    created_date: datetime | None
    def validate_business_rules(self) -> FlextResult[None]: ...
    def validate_domain_rules(self) -> FlextResult[None]: ...
    def get_column_by_name(self, column_name: str) -> FlextDbOracleColumn | None: ...
    @property
    def column_names(self) -> list[str]: ...
    @property
    def qualified_name(self) -> str: ...
    @property
    def primary_key_columns(self) -> list[FlextDbOracleColumn]: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> object: ...

class FlextDbOracleSchema(ValidationMixin, FlextValueObject):
    name: str
    tables: list[FlextDbOracleTable]
    created_date: datetime | None
    default_tablespace: str | None
    def validate_business_rules(self) -> FlextResult[None]: ...
    def validate_domain_rules(self) -> FlextResult[None]: ...
    def get_table_by_name(self, table_name: str) -> FlextDbOracleTable | None: ...
    @property
    def table_count(self) -> int: ...
    @property
    def total_columns(self) -> int: ...
    def get_table(self, table_name: str) -> FlextDbOracleTable | None: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> object: ...

class FlextDbOracleMetadataManager:
    def __init__(self, connection: FlextDbOracleConnection) -> None: ...
    def get_table_metadata(
        self, table_name: str, schema_name: str | None = None
    ) -> FlextResult[FlextDbOracleTable]: ...
    def get_schema_metadata(
        self, schema_name: str
    ) -> FlextResult[FlextDbOracleSchema]: ...
