from typing import Self

from flext_core import FlextContainer, FlextResult
from flext_observability import FlextHealthCheck as FlextHealthCheck, FlextTrace

__all__ = [
    "FlextDbOracleErrorHandler",
    "FlextDbOracleObservabilityManager",
    "FlextDbOracleOperationTracker",
    "FlextHealthCheck",
]

class FlextDbOracleObservabilityManager:
    def __init__(self, container: FlextContainer, context_name: str) -> None: ...
    def log_error_with_context(
        self, error_type: str, error: str | Exception, **context: str
    ) -> None: ...
    def record_error_metric(self, error_type: str, **tags: str) -> None: ...
    def initialize(self) -> FlextResult[None]: ...
    def create_trace(self, operation: str, **attributes: object) -> FlextTrace: ...
    def record_metric(
        self, name: str, value: float, unit: str = "", **tags: str
    ) -> None: ...
    def create_health_check(
        self, status: str, message: str, metrics: dict[str, object] | None = None
    ) -> FlextResult[FlextHealthCheck]: ...
    def finish_trace(
        self,
        trace: FlextTrace,
        duration_ms: int,
        status: str = "success",
        error: str | None = None,
    ) -> FlextTrace: ...
    def get_current_timestamp(self) -> str: ...
    def is_monitoring_active(self) -> bool: ...

class FlextDbOracleOperationTracker:
    def __init__(
        self,
        observability: FlextDbOracleObservabilityManager,
        operation: str,
        **attributes: object,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object,
    ) -> None: ...
    def record_metric(
        self, name: str, value: float, unit: str = "", **tags: str
    ) -> None: ...
    def get_execution_time_ms(self) -> float: ...

class FlextDbOracleErrorHandler:
    def __init__(self, observability: FlextDbOracleObservabilityManager) -> None: ...
    def handle_connection_error(self, error: str | None) -> None: ...
    def handle_config_error(self) -> None: ...
    def handle_query_error(
        self, error: str, sql: str | None = None
    ) -> FlextResult[None]: ...
    def handle_plugin_error(
        self, plugin_name: str, error: str
    ) -> FlextResult[None]: ...
